### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-1-infografia-Nancy-0714#1]
[Infografía_Nancy Olivera.pdf](https://github.com/user-attachments/files/16811766/Infografia_Nancy.Olivera.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días compañera, excelente trabajo.
Porcentaje obtenido en base a la rúbrica: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
